steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
    # build the container image
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/engaged-iridium-282801/productservice:1.0", "--build-arg=JAR_FILE=target/*.jar", "."]
    # push container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/engaged-iridium-282801/productservice:1.0"]
    # deploy container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=k8s-config-file.yaml
    - --image=gcr.io/engaged-iridium-282801/productservice:1.0
    - --location=us-east1-b
    - --cluster=cluster-1
    
    
