---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "productservice"
  namespace: "default"
  labels:
    app: "productservice"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "productservice"
  template:
    metadata:
      labels:
        app: "productservice"
    spec:
      containers:
      - name: "productservice-1"
        image: "gcr.io/engaged-iridium-282801/productservice:1.0"
        ports:
          - containerPort: 8080   
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "productservice-hpa-iyf2"
  namespace: "default"
  labels:
    app: "productservice"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "productservice"
    apiVersion: "apps/v1"
  minReplicas: 2
  maxReplicas: 3
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: productservice
spec:
  selector:
    app: productservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
