apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice
spec:
  selector:
    matchLabels:
      app: productservice
  replicas: 2
  template:
    metadata:
      labels:
        app: productservice
    spec:
      containers:
        - name: productservice
          image: gcr.io/engaged-iridium-282801/productservice:1.0
          ports:
            - containerPort: 8080   
---
apiVersion: v1
kind: Service
metadata:
  name: productservice
spec:
  selector:
    app: productservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  